# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('content', models.CharField(max_length=250)),
            ],
        ),
    ]
